import React, { useEffect, useState } from 'react';
import { Modal } from '../../ui/Modal';
import { Button } from '../../ui/Button';
import { apiClient } from '../../../services/api';
import { ProviderDetail, ProviderConnectionSummary, CreateConnectionPayload, UpdateConnectionPayload } from '../../../types/providers';

interface Props {isOpen: boolean; onClose: () => void; provider: ProviderDetail | null; connectionToEdit?: ProviderConnectionSummary | null; onSubmit: (id: string, payload: CreateConnectionPayload | UpdateConnectionPayload, connectionId?: string) => Promise<void>}
const defaults = {name: 'Demo HTTP', mode: 'DEMO', connectionType: 'HTTP_REST', environment: 'SANDBOX', host: 'demo.invalid', port: 443, priority: 1, tlsEnabled: false, enabled: false,
  smppDirection: 'CLIENT', listenAddress: '0.0.0.0', allowedProviderIps: '95.154.228.78', publicHost: '76.13.217.198',
  systemId: '', systemType: '', throughputTps: 10, windowSize: 10, enquireLinkIntervalSec: 30, reconnectIntervalSec: 10,
  sourceTon: 5, sourceNpi: 0, destTon: 1, destNpi: 1, adapter: 'generic', healthUrl: '', sendUrl: '', authType: 'bearer', authHeader: 'X-API-Key',
  webhookAuth: 'hmac', webhookPublicKey: '', fromField: 'from', toField: 'to', bodyField: 'body', messageIdPath: 'id', credentialRefLabel: 'Carrier credentials'};
export const ConnectionEditor: React.FC<Props> = ({isOpen,onClose,provider,connectionToEdit,onSubmit}) => {
  const [form,setForm] = useState<Record<string,any>>({...defaults});
  const [secrets,setSecrets] = useState({apiKey:'',username:'',password:'',webhookSecret:''});
  const [busy,setBusy] = useState(false); const [notice,setNotice] = useState(''); const [error,setError] = useState('');
  useEffect(() => {
    const initial = {...defaults};
    if (connectionToEdit) for (const key of Object.keys(defaults)) if ((connectionToEdit as any)[key] !== undefined) (initial as any)[key] = (connectionToEdit as any)[key];
    setForm(initial); setSecrets({apiKey:'',username:'',password:'',webhookSecret:''}); setNotice('');setError('');
  },[connectionToEdit,isOpen]);
  if (!provider) return null;
  const http = form.connectionType === 'HTTP_REST'; const incoming = form.smppDirection === 'SERVER'; const demo = form.mode === 'DEMO';
  const field = (key: string, label: string, type='text', placeholder='') => <label key={key} className="block text-xs space-y-1"><span>{label}</span><input aria-label={label} type={type} placeholder={placeholder} value={form[key] ?? ''} onChange={e=>setForm({...form,[key]:type==='number'? Number(e.target.value):e.target.value})} className="glass-input w-full px-3 py-2" /></label>;
  const select = (key: string,label: string,options: string[]) => <label className="block text-xs space-y-1"><span>{label}</span><select aria-label={label} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value,...(key==='connectionType'?{port:e.target.value==='HTTP_REST'?443:2775}:{}),...((key==='mode'||key==='smppDirection')?{enabled:false}:{})})} className="glass-input w-full px-3 py-2">{options.map(v=><option key={v}>{v}</option>)}</select></label>;
  const secretField = (key: keyof typeof secrets,label: string) => <label key={key} className="block text-xs space-y-1"><span>{label}</span><input aria-label={label} type="password" autoComplete="new-password" value={secrets[key]} placeholder={connectionToEdit?'Leave blank to keep saved value':'Enter secret'} onChange={e=>setSecrets({...secrets,[key]:e.target.value})} className="glass-input w-full px-3 py-2" /></label>;
  const runTest = async (sample: boolean) => {
    if (!connectionToEdit) return; setBusy(true);setNotice('');setError('');
    try {
      const url = sample ? `/api/providers/${provider.id}/connections/${connectionToEdit.id}/send` : `/api/providers/${provider.id}/test-connection?connectionId=${encodeURIComponent(connectionToEdit.id)}`;
      const response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${apiClient.getToken()}`,'Content-Type':'application/json'},body:sample?JSON.stringify({from:'DEMO',to:'+15555550123',body:'Demo connection test. No real SMS is sent.',idempotencyKey:crypto.randomUUID()}):undefined});
      const data=await response.json(); if(!response.ok)throw Error(data.error?.message || 'Test failed');
      setNotice(data.data?.message || data.message || 'Test completed');
    } catch(e:any){setError(e.message);} finally{setBusy(false);}
  };
  return <Modal isOpen={isOpen} onClose={onClose} title={connectionToEdit?'Edit carrier connection':'Add carrier connection'} maxWidth="2xl">
    <form className="p-5 space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSubmit(provider.id,{...form,...(!demo?{secrets}: {})} as any,connectionToEdit?.id);onClose();}catch(e:any){setError(e.message || 'Connection could not be saved');}finally{setBusy(false);}}}>
      <p className="text-xs p-3 bg-[var(--glass-bg-hover)] border border-[var(--glass-border)] rounded">{demo?'DEMO — Local simulation only. No external connection, SMS delivery or billing. Change Mode to LIVE when your provider details are ready.':'LIVE — Saving an enabled connection can start a real carrier session. Secrets are encrypted on the server and never returned in this form.'}</p>
      <div className="grid sm:grid-cols-2 gap-4">{field('name','Connection name')}{select('mode','Mode',['DEMO','LIVE'])}{select('connectionType','Protocol',['HTTP_REST','SMPP_TRANSCEIVER','SMPP_TRANSMITTER','SMPP_RECEIVER'])}{select('environment','Environment',['SANDBOX','PRODUCTION'])}</div>
      {!http && <section className="space-y-3 border border-[var(--glass-border)] p-3 rounded">
        <label className="block text-xs space-y-1"><span>Who starts the connection?</span><select aria-label="SMPP connection direction" value={form.smppDirection} onChange={e=>setForm({...form,smppDirection:e.target.value,enabled:false})} className="glass-input w-full px-3 py-2"><option value="CLIENT">Connect to Provider — we bind to their server</option><option value="SERVER">Accept Provider Connection — provider binds to us</option></select></label>
        <p className="text-xs text-[var(--text-secondary)]">{incoming?'We act as the SMPP server. The provider uses the username, password and port you configure here.':'We act as the SMPP client. Enter the host, port and credentials issued by your provider.'}</p>
        {incoming && <><div className="grid sm:grid-cols-2 gap-4">{field('listenAddress','Local listen address','text','127.0.0.1')}{field('allowedProviderIps','Allowed provider IPs','text','95.154.228.78')}{field('publicHost','Our public IP or hostname','text','Your VPS IP or forwarded public address')}{demo&&field('port','Our listening port','number')}</div><p className="text-xs text-[var(--text-tertiary)]">127.0.0.1 is local-only. For a hosted listener, choose the intended server interface (0.0.0.0 for all IPv4 interfaces). Public access requires a reachable IP, firewall rule and port forwarding if behind a router. This form does not open router or firewall ports.</p>{!demo&&form.tlsEnabled&&<p className="text-xs">Server TLS certificate and key files must be configured by the host administrator.</p>}</>}
      </section>}
      {!demo && <>
        {http ? <div className="grid sm:grid-cols-2 gap-4">{select('adapter','Provider format',['generic','twilio','telnyx','sinch'])}{select('authType','HTTP authentication',['bearer','basic','header','none'])}{field('healthUrl','Read-only test URL','url','https://api.provider.com/account')}{field('sendUrl','Send SMS URL','url','https://api.provider.com/messages')}{form.authType==='header'&&field('authHeader','API key header')}{form.authType==='basic'?<>{secretField('username','HTTP username')}{secretField('password','HTTP password')}</>:form.authType!=='none'&&secretField('apiKey','API key')}</div> : <div className="grid sm:grid-cols-2 gap-4">{!incoming&&field('host','Provider SMPP host')}{field('port',incoming?'Our listening port':'Provider SMPP port','number')}{field('systemId',incoming?'Username we give the provider':'Provider System ID')}{secretField('password','SMPP password')}{field('throughputTps','Messages per second','number')}{field('windowSize','Send window','number')}<label className="text-xs flex items-center gap-2"><input type="checkbox" checked={form.tlsEnabled} onChange={e=>setForm({...form,tlsEnabled:e.target.checked})}/>{incoming?'Use server TLS certificate':'Use TLS with certificate verification'}</label></div>}
        <details className="border border-[var(--glass-border)] p-3 rounded"><summary className="text-xs font-semibold cursor-pointer">Callback authentication and advanced settings</summary><div className="grid sm:grid-cols-2 gap-4 mt-4">{select('webhookAuth','Callback authentication',['hmac','twilio','telnyx','bearer'])}{form.webhookAuth==='telnyx'?field('webhookPublicKey','Telnyx public key'):secretField('webhookSecret','Callback secret / Twilio auth token')}{field('priority','Connection priority','number')}{http?<>{field('fromField','Sender field')}{field('toField','Recipient field')}{field('bodyField','Message field')}{field('messageIdPath','Response message ID path')}</>:<>{field('systemType','System type')}{field('sourceTon','Source TON','number')}{field('sourceNpi','Source NPI','number')}{field('destTon','Destination TON','number')}{field('destNpi','Destination NPI','number')}{field('enquireLinkIntervalSec','Heartbeat seconds','number')}{field('reconnectIntervalSec','Reconnect seconds','number')}</>}</div></details>
        <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>{incoming&&!http?'Enable our SMPP listener to accept authenticated provider binds':'Enable live callbacks/sending and automatically start SMPP'}</label>
      </>}
      {connectionToEdit&&<div className="space-y-2 text-xs">{http?<p>Callback path: <code className="break-all">/api/messages/callbacks/{connectionToEdit.id}</code></p>:incoming?<div className="border border-[var(--glass-border)] p-3 space-y-1"><p>Details to give the provider after saving LIVE settings:</p><p>Our IP: {form.publicHost || 'Not configured — do not use the laptop private IP'}</p><p>Username: {form.systemId || 'Not configured'}</p><p>Port: {form.port}</p><p>Bind mode: {form.connectionType.replace('SMPP_','')}</p><p>TLS: {form.tlsEnabled?'Yes':'No'}</p><p>Password: share separately through a secure channel. Saved passwords are never displayed.</p></div>:<p>The provider must allow our outbound public IP.</p>}<div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="secondary" disabled={busy} onClick={()=>runTest(false)}>Test saved connection</Button>{(connectionToEdit as any).mode==='DEMO'&&<Button type="button" size="sm" variant="secondary" disabled={busy} onClick={()=>runTest(true)}>Simulate sample SMS</Button>}</div></div>}
      {error&&<p role="alert" className="text-xs border border-[var(--glass-border)] p-3">{error}</p>}{notice&&<p role="status" className="text-xs border border-[var(--glass-border)] p-3">{notice}</p>}
      <div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" isLoading={busy}>Save connection</Button></div>
    </form>
  </Modal>;
};
