import { Router } from 'express';
import { MessagingController } from '../controllers/messaging.controller';
import { CarrierController } from '../controllers/carrier.controller';
import { authenticate, requirePermission, requireRole } from '../middlewares/auth.middleware';
export const messagingRouter = Router();
messagingRouter.post('/callbacks/:connectionId', CarrierController.callback);
messagingRouter.post('/webhooks/twilio/:providerId', CarrierController.callback);
messagingRouter.post('/webhooks/telnyx/:providerId', CarrierController.callback);
messagingRouter.post('/webhooks/sinch/:providerId', CarrierController.callback);
messagingRouter.use(authenticate);
messagingRouter.get('/stream', requirePermission('sms.view'), MessagingController.stream);
messagingRouter.post('/inbound', requireRole('SUPER_ADMIN'), MessagingController.ingest);
messagingRouter.get('/', requirePermission('sms.view'), MessagingController.list);
messagingRouter.get('/:id', requirePermission('sms.view'), MessagingController.getById);
