import React, {useMemo, useState} from 'react';
import {DataTableToolbar, ColumnVisibility} from '../ui/DataTableToolbar';
export const AgentHeading = ({title,group,description}:{title:string;group:string;description:string}) => <div className="agent-heading"><h1>{title}</h1><nav>Home <span>»</span> {group} <span>»</span> {title}</nav><p>{description}</p></div>;
export function AgentReferenceTable({title,columns,rows,actions,extra,loading,error,footer}:{title:string;columns:{key:string;label:string}[];rows:Record<string,any>[];actions?:(r:any)=>React.ReactNode;extra?:React.ReactNode;loading?:boolean;error?:string;footer?:React.ReactNode}){
 const [cols,setCols]=useState<ColumnVisibility[]>(columns.map(c=>({...c,visible:true}))),[search,setSearch]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(25),[sort,setSort]=useState({key:columns[0].key,dir:1});
 const data=useMemo(()=>rows.filter(r=>columns.some(c=>String(r[c.key]??'').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>String(a[sort.key]??'').localeCompare(String(b[sort.key]??''),undefined,{numeric:true})*sort.dir),[rows,search,sort,columns]);
 const current=Math.min(page,Math.max(1,Math.ceil(data.length/size))); const toolbar={exportData:data,columnDefs:cols,onColumnVisibilityChange:(key:string,visible:boolean)=>setCols(cs=>cs.map(c=>c.key===key?{...c,visible}:c)),currentPage:current,totalItems:data.length,pageSize:size,onPageChange:setPage,onPageSizeChange:(n:number)=>{setSize(n);setPage(1);},searchValue:search,onSearchChange:(s:string)=>{setSearch(s);setPage(1);}};
 return <section className="agent-panel"><div className="agent-panel-title"><h2>{title}</h2>{extra}</div><DataTableToolbar {...toolbar} section="controls"/><div className="overflow-x-auto"><table className="agent-table"><thead><tr>{cols.filter(c=>c.visible).map(c=><th key={c.key}><button onClick={()=>setSort({key:c.key,dir:sort.key===c.key?-sort.dir:1})}>{c.label} {sort.key===c.key?(sort.dir===1?'↑':'↓'):''}</button></th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{loading||error||!data.length?<tr><td colSpan={cols.filter(c=>c.visible).length+(actions?1:0)} className="agent-empty">{loading?'Loading…':error||'No records found.'}</td></tr>:data.slice((current-1)*size,current*size).map((r,i)=><tr key={r.id||i}>{cols.filter(c=>c.visible).map(c=><td key={c.key}>{r[c.key]??'—'}</td>)}{actions&&<td><div className="agent-actions">{actions(r)}</div></td>}</tr>)}</tbody></table></div>{footer}<DataTableToolbar {...toolbar} section="pagination"/></section>;
}
export async function allPages(load:(page:number)=>Promise<any>){let result:any[]=[];for(let page=1;page<=100;page++){const res=await load(page);const rows=res?.items||[];result.push(...rows);if(rows.length===0||page>=(res.totalPages||Math.ceil((res.total||rows.length)/100)))return result;}throw Error('Too many records. Narrow the reporting period.');}
