import React,{useEffect,useMemo,useState} from 'react';
import {apiClient} from '../../services/api';
import {AgentHeading,AgentReferenceTable,allPages} from './AgentReferenceTable';
const columns=[['date','Date'],['range','Range'],['number','Number'],['cli','CLI'],['sms','SMS'],['client','Client'],['currency','Currency'],['myPayout','My Payout'],['clientPayout','Client Payout'],['status','Status']].map(([key,label])=>({key,label}));
const today=new Date().toISOString().slice(0,10);
const initial={from:today+'T00:00',to:today+'T23:59',range:'',client:'',number:'',cli:''};
const money=(n:number)=>n.toFixed(4).replace(/0+$/,'').replace(/\.$/,'.00');
export const CdrStatisticsView:React.FC=()=>{
 const [raw,setRaw]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState(initial),[filter,setFilter]=useState(initial),[groups,setGroups]=useState<string[]>([]);
 async function load(){setLoading(true);setError('');try{setRaw(await allPages(page=>apiClient.getCdrs({page,limit:100,from:filter.from+'Z',to:filter.to+':59Z'} as any)));}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[filter]);
 const options=(key:string)=>[...new Set(raw.map(r=>key==='range'?r.rangeName:r.clientName).filter(Boolean))];
 const records=useMemo(()=>raw.map(c=>({id:c.id,date:(c.receivedAt||c.createdAt||'').replace('T',' ').slice(0,19),range:c.rangeName||'—',number:c.e164||c.toNumber||'—',cli:c.fromNumber||'—',sms:c.body||'—',client:c.clientName||'—',currency:c.currency||'USD',myPayout:Number(c.agentCommissionDecimal||0),clientPayout:Number(c.clientChargeDecimal||0),status:c.status||'Billed'})).filter(r=>(!filter.range||r.range===filter.range)&&(!filter.client||r.client===filter.client)&&r.number.includes(filter.number)&&r.cli.toLowerCase().includes(filter.cli.toLowerCase())),[raw,filter]);
 const grouped=useMemo(()=>{if(!groups.length)return records;const map=new Map<string,any>();for(const r of records){const parts=groups.map(g=>g==='hour'?r.date.slice(0,13):g==='day'?r.date.slice(0,10):g==='month'?r.date.slice(0,7):(r as any)[g]);const key=JSON.stringify([r.currency,...parts]);if(!map.has(key)){const item:any={id:key,date:'—',range:'—',number:'—',cli:'—',client:'—',currency:r.currency,status:'—',myPayout:0,clientPayout:0,count:0};groups.forEach((g,i)=>item[['hour','day','month'].includes(g)?'date':g]=parts[i]);map.set(key,item);}const item=map.get(key);item.count++;item.myPayout+=r.myPayout;item.clientPayout+=r.clientPayout;item.sms=`${item.count} SMS`;}return [...map.values()];},[records,groups]);
 const rows=grouped.map(r=>({...r,myPayout:money(r.myPayout),clientPayout:money(r.clientPayout)}));
 function exportReport(){const quote=(s:any)=>'"'+String(s??'').replace(/"/g,'""')+'"';const blob=new Blob([[columns.map(c=>quote(c.label)).join(','),...rows.map(r=>columns.map(c=>quote((r as any)[c.key])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cdr-report.csv';a.click();URL.revokeObjectURL(url);}
 return <div className="agent-reference"><AgentHeading title="Detailed Reports" group="CDR & Statistics" description="Detailed records of every inbound SMS."/><form className="agent-panel agent-report-filters" onSubmit={e=>{e.preventDefault();setFilter({...draft});}}><div className="agent-filter-row">{(['from','to'] as const).map(key=><label key={key}>{key}<input type="datetime-local" required value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{(['range','client'] as const).map(key=><label key={key}>Filter {key}<select value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}><option value="">All {key}s</option>{options(key).map(v=><option key={v}>{v}</option>)}</select></label>)}{(['number','cli'] as const).map(key=><label key={key}>Search {key}<input placeholder={`Search ${key.toUpperCase()}`} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<button type="button" onClick={exportReport}>Export Report</button><button className="agent-primary" type="submit">Show Report</button></div><div className="agent-group-row">Group by {['Hour','Day','Month','Range','Number','CLI','Client','Currency','Status'].map(label=><label key={label}><input type="checkbox" checked={groups.includes(label.toLowerCase())} onChange={e=>setGroups(gs=>e.target.checked?[...gs,label.toLowerCase()]:gs.filter(g=>g!==label.toLowerCase()))}/>{label}</label>)}</div></form><AgentReferenceTable title="CDR Reports & Stats" columns={columns} rows={rows} loading={loading} error={error} footer={<div className="agent-totals"><span>Total SMS <strong>{records.length}</strong></span>{[...new Set(records.map(r=>r.currency))].map(currency=><span key={currency}>{currency} · My Payout <strong>{money(records.filter(r=>r.currency===currency).reduce((n,r)=>n+r.myPayout,0))}</strong> · Client Payout <strong>{money(records.filter(r=>r.currency===currency).reduce((n,r)=>n+r.clientPayout,0))}</strong></span>)}</div>}/></div>;
};
