import React,{useEffect,useMemo,useState} from 'react';
import {apiClient} from '../../services/api';
import {AgentHeading,AgentReferenceTable} from './AgentReferenceTable';
const columns=[['date','Date'],['for','For'],['term','Term'],['currency','Currency'],['payout','Payout'],['cdrs','CDRs'],['notes','Notes'],['withdrawable','Withdrawable On'],['maturity','Maturity']].map(([key,label])=>({key,label}));
export const CreditNotesView:React.FC=()=>{
 const now=new Date(),start=new Date();start.setMonth(start.getMonth()-2);const initial={from:start.toISOString().slice(0,10),to:now.toISOString().slice(0,10),status:'All'};
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[draft,setDraft]=useState(initial),[filter,setFilter]=useState(initial);
 useEffect(()=>{let active=true;(async()=>{try{const wallets=await apiClient.getWallets();const result=await Promise.all((Array.isArray(wallets)?wallets:[]).map(async(w:any)=>{let entries:any[]=[];for(let page=1;page<=100;page++){const r=await apiClient.getWalletLedger(w.id,{limit:100,page} as any);const batch=r.entries||r.items||[];entries.push(...batch);if(!batch.length||page>=(r.totalPages||Math.ceil((r.total||batch.length)/100)))break;}return entries.filter(e=>e.direction==='CREDIT').map(e=>{const due=e.withdrawableOn||e.maturesAt;return{id:e.id,date:(e.createdAt||'').slice(0,10),for:e.category||'Credit',term:e.payoutTerm||'—',currency:e.currency||w.currency||'USD',payout:Number(e.amountDecimal??e.amount??0).toFixed(4),cdrs:e.cdrCount??'—',notes:e.description||'—',withdrawable:due?String(due).slice(0,10):'—',maturity:due?(new Date(due).getTime()<=Date.now()?'Available':'Pending'):'Not specified'};});}));if(active)setRows(result.flat());}catch(e:any){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const filtered=useMemo(()=>rows.filter(r=>r.date>=filter.from&&r.date<=filter.to&&(filter.status==='All'||r.maturity===filter.status)),[rows,filter]);
 return <div className="agent-reference"><AgentHeading title="Credit Notes" group="Finance" description="Credit notes for your account. You can request payment after the due date."/><form className="agent-panel agent-credit-filters" onSubmit={e=>{e.preventDefault();setFilter({...draft});}}>{(['from','to'] as const).map(key=><label key={key}>{key}<input required type="date" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['All','Available','Pending','Not specified'].map(s=><option key={s}>{s}</option>)}</select></label><button className="agent-primary" type="submit">Show Report</button></form><AgentReferenceTable title="Credit Notes" columns={columns} rows={filtered} loading={loading} error={error}/></div>;
};
