import React,{useEffect,useState} from 'react';
import {Plus,Eye,Pencil,RotateCcw,Power} from 'lucide-react';
import {apiClient} from '../../services/api';
import {Modal} from '../ui/Modal';
import {AgentHeading,AgentReferenceTable,allPages} from './AgentReferenceTable';
const columns=['Username','Name','Email','Contact','Teams','Balance','Active'].map(label=>({key:label.toLowerCase(),label}));
const blank={username:'',name:'',email:'',contact:'',teams:'',password:''};
export const MyClientsView:React.FC=()=>{
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[form,setForm]=useState(blank),[modal,setModal]=useState<'new'|'edit'|'view'|'reset'|null>(null),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 async function load(){setLoading(true);setError('');try{const data=await allPages(page=>apiClient.getClients({page,limit:100}));setRows(data.map(c=>({...c,username:c.username||'—',name:c.name||[c.firstName,c.lastName].filter(Boolean).join(' ')||'—',email:c.email?.endsWith('@clients.invalid')?'':c.email||'',contact:c.contact||c.contactPhone||'',teams:c.teams||'',balance:`$${Number(c.balance||0).toFixed(2)}`,active:c.status==='ACTIVE'?'✓':'—'})));}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function open(kind:typeof modal,r?:any){setSelected(r||null);setForm(r?{username:r.username,name:r.name==='—'?'':r.name,email:r.email,contact:r.contact,teams:r.teams,password:''}:blank);setFormError('');setModal(kind);}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError('');try{if(modal==='reset'){await apiClient.resetClientPassword(selected.id,{newPassword:form.password});}else{const [firstName='',...last]=form.name.trim().split(/\s+/);const payload={username:form.username,firstName,lastName:last.join(' '),email:form.email,contact:form.contact,teams:form.teams,companyName:'',password:form.password};if(modal==='edit')await apiClient.updateClient(selected.id,{firstName,lastName:last.join(' '),contact:form.contact,teams:form.teams});else await apiClient.createClient(payload);}setModal(null);await load();}catch(e:any){setFormError(e.message||'Unable to save client');}finally{setBusy(false);}}
 async function toggle(r:any){if(!window.confirm(`${r.status==='ACTIVE'?'Disable':'Enable'} ${r.username}?`))return;try{await apiClient.updateClientStatus(r.id,r.status==='ACTIVE'?'SUSPENDED':'ACTIVE','Agent portfolio update');await load();}catch(e:any){setError(e.message);}}
 return <div className="agent-reference"><AgentHeading title="My Clients" group="Users" description="Clients are the end users. They get numbers from you and make traffic on them."/><AgentReferenceTable title="Manage Clients" columns={columns} rows={rows} loading={loading} error={error} extra={<button className="agent-primary" aria-label="New client" onClick={()=>open('new')}><Plus size={16}/></button>} actions={r=><><button title="View client" aria-label={`View ${r.username}`} onClick={()=>open('view',r)}><Eye size={14}/></button><button title="Edit client" aria-label={`Edit ${r.username}`} onClick={()=>open('edit',r)}><Pencil size={14}/></button><button title="Reset password" aria-label={`Reset password for ${r.username}`} onClick={()=>open('reset',r)}><RotateCcw size={14}/></button><button title={r.status==='ACTIVE'?'Disable client':'Enable client'} aria-label={`Toggle ${r.username}`} onClick={()=>toggle(r)}><Power size={14}/></button></>}/>
 <Modal isOpen={!!modal} onClose={()=>setModal(null)} title={modal==='new'?'New client':modal==='edit'?'Edit client':modal==='reset'?'Reset password':'Client details'} maxWidth="2xl"><form onSubmit={save} className="agent-client-form">{(modal==='reset'?['password']:['username','name','email','contact','teams',...(modal==='new'?['password']:[])]).map(key=><label key={key}>{key}{['name','email','contact','teams'].includes(key)?' (optional)':''}<input autoComplete={key==='password'?'new-password':'off'} type={key==='password'?'password':key==='email'?'email':'text'} required={key==='username'||key==='password'} minLength={key==='password'?8:key==='username'?3:undefined} maxLength={key==='username'?64:undefined} pattern={key==='username'?'[A-Za-z0-9_.-]{3,64}':undefined} disabled={modal==='view'||modal==='edit'&&['username','email'].includes(key)} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>{key==='username'&&<small>3–64 chars · letters, digits, underscore, dot and hyphen.</small>}{key==='password'&&<small>At least 8 characters.</small>}</label>)}{modal==='new'&&!form.email&&<small>Without an email, the login address will be {form.username||'username'}@clients.invalid. No email is sent to this address.</small>}{formError&&<p role="alert">{formError}</p>}<div className="agent-form-footer"><button type="button" onClick={()=>setModal(null)}>Cancel</button>{modal!=='view'&&<button disabled={busy} className="agent-primary" type="submit">{busy?'Saving…':modal==='new'?'Create':'Save'}</button>}</div></form></Modal></div>;
};
